// Generated by CoffeeScript 1.6.2
var fn, sq, _funcName, _originFunc, _overrideFunc, _ref;

_ref = [require('simplequeue'), 'createQueue'], sq = _ref[0], _funcName = _ref[1];

fn = sq[_funcName];

_originFunc = function() {
  return fn();
};

sq[_funcName] = _overrideFunc = function() {
  var _r;

  _r = function(_) {
    var _ref1;

    _ref1 = [_['putMessage'], _['getMessage']], _['push'] = _ref1[0], _['shift'] = _ref1[1];
    _['shift']['sync'] = _['getMessageSync'].bind(_);
    return _;
  };
  return _r(_originFunc());
};

module.exports = sq;
